export default [
  [
    'Languages',
    [
      'Java',
      'C',
      'C++',
      'Python',
      'HTML',
      'CSS',
      'JavaScript',
      'TypeScript',
      'SQL',
      'NoSQL',
      'MATLAB',
      'R',
    ],
  ],
  [
    'Developer Tools',
    [
      'Git',
      'Google Cloud Platform',
      'MongoDB',
      'Firebase',
      'Supabase',
      'MySQL',
      'Google APIs',
      'NodeJs',
      'ExpressJs',
      'Flask',
      'Django',
      'Tailwind',
      'ShadCN',
      'Socket',
    ],
  ],
  [
    'Relevant Courseworks',
    [
      'Data Structures and Algorithms',
      'Database Management',
      'Web Development',
      'Computer Networks',
      'Operating Systems',
      'Microprocessors and Microcontrollers',
      'Compiler Design',
      'Artificial Intelligence',
      'AWS Architecture'
    ],
  ],
  [
    'Frameworks',
    [
      'ReactJs',
      'NextJs',
      'Github',
      'Figma',
      'Canva',
    ],
  ],
];
